name: Docker Image CI

# Control when the action will run
on:

  #  Trigger when the workflow will run but for only the main  branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  # Workflow contains multiple jobs

  build_test:

    # The type of runner the job will run on

    runs-on: ubuntu-latest

    # Steps represents a sequemce of taks that will be executed as part of the job.

    steps:
    - uses: actions/checkout@v2

    # Build out the client react image 

    - name: build client image
      run: docker build -t ndohjapan/react-test -f ./client/dockerfile.dev ./client
    
    # Run the test script for the react and add --coverage to ensure that the test exits

    - name: test app
      run: docker run --rm --detach ndohjapan/react-test npm test
  
  push_to_Docker_Hub:

    # The type of runner that the job will run on 

    runs-on: ubuntu-latest

    # build docker image and push to docker hub
    # only if the app build and test successfully
    needs: [build_test]

    steps:

      - uses: actions/checkout@v3

      # Login to docker

      - name: login to docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: build client
        run: docker build -t ndohjapan/multi-client ./client

      - name: build nginx
        run: docker build -t ndohjapan/multi-nginx ./nginx

      - name: build server
        run: docker build -t ndohjapan/multi-server ./server

      - name: build worker
        run: docker build -t ndohjapan/multi-worker ./worker

      - name: push client to docker hub
        run: docker push ndohjapan/multi-client

      - name: push nginx to docker hub
        run: docker push ndohjapan/multi-nginx

      - name: push server to docker hub
        run: docker push ndohjapan/multi-server

      - name: push worker to docker hub
        run: docker push ndohjapan/multi-worker

  deploy_to_EBS:

    # The type of runner that the job will run on 

    runs-on: ubuntu-latest

    # build docker image and push to docker hub
    # only if the app build and test successfully
    needs: [push_to_Docker_Hub]

    steps:

      - uses: actions/checkout@v3

      - name: Generate deployment package
        run: zip -r deploy.zip * .[^.]* -x "**node_modules**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          version_label: "e-learn-${{ steps.format-time.outputs.replaced }}"
          region: eu-west-2
          deployment_package: deploy.zip

      - name: Deployed!
        run: echo App deployed to ELB

