name: Docker Image CI

# Control when the action will run
on:

  #  Trigger when the workflow will run but for only the main  branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  # Workflow contains multiple jobs

  build_test:

    # The type of runner the job will run on

    runs-on: ubuntu-latest

    # Steps represents a sequemce of taks that will be executed as part of the job.

    steps:
    - uses: actions/checkout@v2

    # Login to docker

    - name: login to docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # Build out the client react image 

    - name: build client image
      run: docker build -t ndohjapan/react-test -f ./client/dockerfile.dev ./client
    
    # Run the test script for the react and add --coverage to ensure that the test exits

    - name: test app
      run: docker run --rm --detach ndohjapan/react-test npm test
  
  pusht_to_Docker_Hub:

    # The type of runner that the job will run on 

    runs-on: ubuntu-latest

    # build docker image and push to docker hub
    # only if the app build and test successfully
    needs: [build_test]

    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build client and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./dockerfile
          push: true
          tags: ndohjapan/multi-client:latest

      - name: Build nginx and push
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./dockerfile
          push: true
          tags: ndohjapan/multi-nginx:latest

      - name: Build server and push
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./dockerfile
          push: true
          tags: ndohjapan/multi-server:latest

      - name: Build worker and push
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          file: ./dockerfile
          push: true
          tags: ndohjapan/multi-worker:latest
